twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/tailwind_2_layout.html.twig']
    paths:
        '%kernel.project_dir%/assets/images/icons': icons

when@test:
    twig:
        strict_variables: true
